# Use a slim Python image
FROM python:3.12-slim

# Install LaTeX and PostgreSQL dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    texlive-latex-base \
    texlive-latex-extra \
    texlive-fonts-recommended \
    libpq-dev gcc \
    && rm -rf /var/lib/apt/lists/*

# Install specific Python packages
RUN pip install --no-cache-dir jinja2 sqlalchemy psycopg2-binary

# Set working directory
WORKDIR /app

# Copy the builder script
COPY src/python/latex_builder.py /app/latex_builder.py

# Copy the LaTeX template and the logos so pdflatex has access to them
COPY templates/ /app/templates/
COPY data/logo/ /app/data/logo/

# Command to run the script
CMD ["python", "/app/latex_builder.py"]
# [ ] Changed for the devcontainer

# ENTRYPOINT ["python", "/app/latex_builder.py"]